### ISSUE TITLE
ModuleNotFoundError: No module named 'empower_functions.monkey_patch'

### ISSUE THREAD

**Issue by ChristianWeyer** [empower-ai/empower-functions#3]
After
`pip install empower-functions`

I run the model:
```
python -m empower_functions.server --model "ggml-model-f16.gguf" --chat_format empower-functions
```

And get this error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/abc/miniconda3/envs/empower-functions/lib/python3.11/site-packages/empower_functions/server.py", line 18, in <module>
    from empower_functions.monkey_patch.app import patch_app
ModuleNotFoundError: No module named 'empower_functions.monkey_patch'
```

**Comment by dyang415** [comment]
Hi @ChristianWeyer thanks for reporting the issue, we have just released the new version of the pip package 0.1.6 which should have this issue fixed, please let us if there's anything else we can help!
